einkaufsliste_project/einkaufsliste/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "einkaufsliste"

urlpatterns = [
    path('', views.index, name='index'),
    path('index2', views.index2, name='index2'),
    path('delete_liste/<int:liste_id>/', views.delete_liste, name='delete_liste'),
    path('new_item/<int:liste_id>/', views.new_item, name='new_item'),
    path('speichern_item/<int:liste_id>/', views.speichern_item, name='speichern_item'),
    path('change_item/<int:item_id>/', views.change_item, name='change_item'),
    path('speichern_change/<int:item_id>/', views.speichern_change, name='speichern_change'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('new_liste', views.new_liste, name='new_liste'),
]

einkaufsliste_project/einkaufsliste_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('einkaufsliste/', include('einkaufsliste.urls'))
]

einkaufsliste_project/einkaufsliste/models.py
from django.db import models

class Liste(models.Model):
    name = models.CharField("name of list", max_length = 200)
    date = models.DateTimeField("date of list")
    
    def __str__(self):
        return self.name


class Eintrag(models.Model):
    name = models.CharField("name of eintrag", max_length = 200)
    status = models.BooleanField(default=False)
    menge = models.IntegerField(default=1)
    liste = models.ForeignKey(Liste, on_delete = models.CASCADE)
    category = models.ForeignKey(to="Category", on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField("name of category", max_length=200)

    def __str__(self):
        return self.name

einkaufsliste_project/einkaufsliste/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from . import models
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.utils import timezone


def index(request):
    listen = models.Liste.objects.order_by('-date')
    eintraege = models.Eintrag.objects.all()
    categories = models.Category.objects.all()
    context = {"listen": listen, "eintraege": eintraege, "categories": categories}
    return render(request, "einkaufsliste/index.html", context)


def index2(request):
    eintraege = models.Eintrag.objects.all().order_by('name')
    categories = models.Category.objects.all()
    context = {"eintraege": eintraege, "categories": categories}
    return render(request, "einkaufsliste/index2.html", context)


def delete_liste(request, liste_id):
    try:
        liste = models.Liste.objects.get(id=liste_id)
        liste.delete()
        return HttpResponseRedirect(reverse('einkaufsliste:index'))
    except Liste.DoesNotExist:
        return HttpResponseNotFound("<h2>Liste not found</h2>")


def new_item(request, liste_id):
    liste = models.Liste.objects.get(id=liste_id)
    return render(request, "einkaufsliste/new_item.html", {"liste": liste})


def speichern_item(request, liste_id):
    print(request.POST)
    item = models.Eintrag()
    item.name = request.POST.get("name")
    if request.POST.get("status"):
        item.status = True
    else:
        item.status = False
    try:
        int(request.POST.get("menge"))
        item.menge = request.POST.get("menge")
    except:
        item.menge = 1
    item.liste = models.Liste(id=liste_id)
    if request.POST.get("category"):
        try:
            a = get_object_or_404(models.Category, name=request.POST.get("category"))
            item.category =  models.Category(id=a.id)
        except:
            new_category = models.Category()
            new_category.name = request.POST.get("category")
            new_category.save()
            item.category = request.POST.get("category")

    item.save()
    return HttpResponseRedirect(reverse('einkaufsliste:index'))


def change_item(request, item_id):
    item = models.Eintrag.objects.get(id=item_id)
    return render(request, "einkaufsliste/change_item.html", {"item": item})


def speichern_change(request, item_id):
    print(request.POST)
    item = models.Eintrag.objects.get(id=item_id)
    if request.POST.get("name"):
        item.name = request.POST.get("name")
    if request.POST.get("menge"):
        try:
            int(request.POST.get("menge"))
            item.menge = request.POST.get("menge")
        except:
            item.menge = 1
    if request.POST.get("category"):
        try:
            a = get_object_or_404(models.Category, name=request.POST.get("category"))
            item.category =  models.Category(id=a.id)
        except:
            new_category = models.Category()
            new_category.name = request.POST.get("category")
            new_category.save()
            item.category = request.POST.get("category")
    if request.POST.get("status"):
        item.status = True
    else:
        item.status = False
    
    item.save()
    return HttpResponseRedirect(reverse('einkaufsliste:index'))


def delete_item(request, item_id):
    item = models.Eintrag.objects.get(id=item_id)
    item.delete()
    return HttpResponseRedirect(reverse('einkaufsliste:index'))


def new_liste(request):
    if request.POST.get("name"):
        new_liste = models.Liste()
        new_liste.name = request.POST.get("name")
        new_liste.date = timezone.now()
        new_liste.save()
    else:
        pass
    return HttpResponseRedirect(reverse('einkaufsliste:index'))

    

einkaufsliste_project/einkaufsliste/templates/einkaufsliste/change_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title></title>
</head>
<body>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h3>Ändern "{{item.name}}"</h3>
            <form action="{% url 'einkaufsliste:speichern_change' item.id %}" method="post">
                <div class="form-group">
                    {% csrf_token %}
                    <label for="name">Name von Eintrag:</label><br>
                    <input type="text" class="form-control" placeholder="{{item.name}}" id="name" name="name"><br>
                </div>
                <div class="form-group">
                    <label for="menge">Menge:</label><br>
                    <input type="text" class="form-control" placeholder="{{item.menge}}" id="menge" name="menge"><br> 
                </div> 
                <div class="form-group">
                    <label for="category">Kategorie:</label><br>
                    <input type="text" class="form-control" placeholder="{{item.category}}" id="category" name="category"><br> 
                </div>

                <div class="form-group">      
                    <label for="status">Status</label>
                    <input type="checkbox" name="status" {% if item.status == True %}checked{% endif %} id="status" value="True"><br>
                </div> 
                <button type="submit" class="btn btn-primary" value="change_item">Speichern</button>
                <a class="btn btn-secondary" href="{% url 'einkaufsliste:index' %}" role="button">Zurück</a>
                <a class="btn btn-danger" href="{% url 'einkaufsliste:delete_item' item.id %}" role="button">Löschen</a>
            </form>
        </div>
    </div>
</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

einkaufsliste_project/einkaufsliste/templates/einkaufsliste/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Einkaufsliste</title>
</head>
<body>

<div class="container">
    <div class="row justify-content-around alig">
        <div class="card align-self-center">
            <h1 class="m-3">Einkaufsliste - App</h1>
        </div>
        <div class="card m-3">
            <form action="{% url 'einkaufsliste:new_liste' %}" method="post">
            <div class="form-group m-3">
            {% csrf_token %}
            
                <label for="name">Name von Liste:</label><br>
                <input type="text" class="form-control" id="name" name="name">
            
            
                <button type="submit" class="btn btn-primary mt-3" value="change_item">Neue Liste anlegen</button>
            
            </div>
            </form>
        </div>
    </div>
</div> 
<div class="container mb-5">
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'einkaufsliste:index' %}">Alle Listen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'einkaufsliste:index2' %}">Einträge nach Kategorien</a>
        </li>
      </ul>
</div>    

    {% for liste in listen %}
    <nav class="container navbar navbar-light justify-content-start" style="background-color: #e3f2fd;">
            <span >{{liste.name}}</span>
            <a class="btn btn-link ml-3" data-toggle="collapse" href="#collapse{{liste.name}}" role="button" aria-expanded="false" aria-controls="collapse{{liste.name}}">
                Liste öffnen
              </a>
            <a class="btn btn-primary ml-3" href="{% url 'einkaufsliste:new_item' liste.id %}" role="button">Neuer Eintrag</a>
            <a class="btn btn-outline-danger ml-3" href="{% url 'einkaufsliste:delete_liste' liste.id %}" role="button">Liste löschen</a>
    </nav>

<div class="container">
    <div class="collapse" id="collapse{{liste.name}}">
        <div class="card card-body">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Item</th>
                    <th scope="col">Menge</th>
                    <th scope="col">Kategorie</th>
                    <th scope="col">Status</th>
                    <th scope="col">Item ändern</th>
                </tr>
                </thead>
                <tbody>
                <tr> 
                {% for eintrag in eintraege %}
                    {% if eintrag.liste.name == liste.name %}
                    <th scope="row">{{eintrag.name}}</th>
                    <td>{{eintrag.menge}}</td>
                    <td>{{eintrag.category}}</td>
                    <td>
                        {% if eintrag.status == True %}
                        <div class="spinner-grow text-success" role="status">
                        </div>
                        {% else %}
                        <div class="spinner-grow text-danger" role="status">
                        </div>
                        {% endif %}
                    </td>
                    <td><a class="btn btn-primary ml-3" href="{% url 'einkaufsliste:change_item' eintrag.id %}" role="button">ändern</a></td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
    {% endfor %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

einkaufsliste_project/einkaufsliste/templates/einkaufsliste/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Einkaufsliste</title>
</head>
<body>

<div class="container">
    <div class="row justify-content-around alig">
        <div class="card align-self-center">
            <h1 class="m-3">Einkaufsliste - App</h1>
        </div>
        <div class="card m-3">
            <form action="{% url 'einkaufsliste:new_liste' %}" method="post">
            <div class="form-group m-3">
            {% csrf_token %}
            
                <label for="name">Name von Liste:</label><br>
                <input type="text" class="form-control" id="name" name="name">
            
            
                <button type="submit" class="btn btn-primary mt-3" value="change_item">Neue Liste anlegen</button>
            
            </div>
            </form>
        </div>
    </div>
</div> 
<div class="container mb-5">
    <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'einkaufsliste:index' %}">Alle Listen</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'einkaufsliste:index2' %}">Einträge nach Kategorien</a>
        </li>
      </ul>
</div>  

<div class="container">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Eintrag</th>
            <th scope="col">Menge</th>
            <th scope="col">Kategorie</th>
            <th scope="col">Status</th>
            <th scope="col">Item ändern</th>
          </tr>
        </thead>
        <tbody>
          <tr> 
        {% for eintrag in eintraege %}
            <th scope="row">{{eintrag.name}}</th>
            <td>{{eintrag.menge}}</td>
            <td>{{eintrag.category}}</td>
            <td>
                {% if eintrag.status == True %}
                <div class="spinner-grow text-success" role="status">
                </div>
                {% else %}
                <div class="spinner-grow text-danger" role="status">
                </div>
                {% endif %}
            </td>
            <td><a class="btn btn-primary ml-3" href="{% url 'einkaufsliste:change_item' eintrag.id %}" role="button">ändern</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    
       
    
</div>



<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

einkaufsliste_project/einkaufsliste/templates/einkaufsliste/new_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title></title>
</head>
<body>
<div class="container">
    <div class="card">
        <div class="card-body">
            <h3>Neuer Eintrag für "{{liste.name}}"</h3>
            <form action="{% url 'einkaufsliste:speichern_item' liste.id%}" method="post">
                <div class="form-group">
                    {% csrf_token %}
                    <label for="name">Name von Eintrag:</label><br>
                    <input type="text" class="form-control" id="name" name="name"><br>
                </div>
                <div class="form-group">
                    <label for="menge">Menge:</label><br>
                    <input type="text" class="form-control" id="menge" name="menge"><br> 
                </div> 
                <div class="form-group">
                    <label for="category">Kategorie:</label><br>
                    <input type="text" class="form-control" id="category" name="category"><br> 
                </div>

                <div class="form-group">      
                    <label for="status">Status</label>
                    <input type="checkbox" name="status" id="status" value="True"><br>

                </div> 
                <button type="submit" class="btn btn-primary" value="new_item">Anlegen</button>
                <a class="btn btn-secondary" href="{% url 'einkaufsliste:index' %}" role="button">Zurück</a>
            </form>
        </div>
    </div>
</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>